# Generated by Django 5.2.7 on 2025-10-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_url', models.CharField(blank=True, help_text='URL для запроса файла, например, http://192.168.88.171:5000/download', max_length=255, verbose_name='URL сервиса загрузки')),
                ('download_token', models.CharField(blank=True, max_length=255, verbose_name='Токен сервиса загрузки')),
                ('download_user', models.CharField(blank=True, max_length=100, verbose_name='Пользователь сервиса загрузки')),
                ('download_password', models.CharField(blank=True, max_length=255, verbose_name='Пароль сервиса загрузки')),
                ('db_host', models.CharField(default='localhost', max_length=100, verbose_name='Хост БД')),
                ('db_port', models.IntegerField(default=3306, verbose_name='Порт БД')),
                ('db_name', models.CharField(default='asteriskcdrdb', max_length=100, verbose_name='Имя БД')),
                ('db_user', models.CharField(default='asteriskuser', max_length=100, verbose_name='Пользователь БД')),
                ('db_password', models.CharField(blank=True, help_text='Пароль хранится в открытом виде. Убедитесь, что доступ к серверу ограничен.', max_length=255, verbose_name='Пароль БД')),
                ('ami_host', models.CharField(default='localhost', max_length=100, verbose_name='Хост AMI')),
                ('ami_port', models.IntegerField(default=5038, verbose_name='Порт AMI')),
                ('ami_user', models.CharField(default='admin', max_length=100, verbose_name='Пользователь AMI')),
                ('ami_password', models.CharField(blank=True, help_text='Пароль хранится в открытом виде.', max_length=255, verbose_name='Пароль AMI')),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
            },
        ),
    ]
