# Generated by Django 5.0.6 on 2026-02-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_display_mappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorPayoutRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_system_name', models.CharField(max_length=128, unique=True, verbose_name='Системное имя оператора')),
                ('rate_per_minute', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка за минуту')),
            ],
            options={
                'verbose_name': 'Ставка оператора',
                'verbose_name_plural': 'Ставки операторов',
                'ordering': ['agent_system_name'],
            },
        ),
    ]
