# Generated by Django 5.0.6 on 2026-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_operatorpayoutrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='business_day_end',
            field=models.TimeField(default='18:00', verbose_name='Конец бизнес-дня'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='business_day_start',
            field=models.TimeField(default='09:00', verbose_name='Начало бизнес-дня'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='currency_code',
            field=models.CharField(default='UZS', max_length=8, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='default_payout_rate_per_minute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая цена за минуту'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='sla_target_percent',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=5, verbose_name='Цель SLA, %'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='sla_target_wait_seconds',
            field=models.IntegerField(default=20, verbose_name='SLA порог ожидания, сек'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='ui_language',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name='Язык интерфейса'),
        ),
    ]
