# Generated by Django 5.0.6 on 2026-02-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_generalsettings_business_day_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='transcription_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='API ключ транскрибации'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='transcription_url',
            field=models.CharField(blank=True, help_text='Например: http://198.163.206.26:5085/transcribe', max_length=255, verbose_name='URL сервиса транскрибации'),
        ),
    ]
