# Generated by Django 5.0.6 on 2026-02-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calldate', models.DateTimeField()),
                ('clid', models.CharField(max_length=80)),
                ('src', models.CharField(max_length=80)),
                ('dst', models.CharField(max_length=80)),
                ('dcontext', models.CharField(max_length=80)),
                ('channel', models.CharField(max_length=80)),
                ('dstchannel', models.CharField(max_length=80)),
                ('lastapp', models.CharField(max_length=80)),
                ('lastdata', models.CharField(max_length=80)),
                ('duration', models.IntegerField()),
                ('billsec', models.IntegerField()),
                ('disposition', models.CharField(max_length=45)),
                ('amaflags', models.IntegerField()),
                ('accountcode', models.CharField(max_length=20)),
                ('uniqueid', models.CharField(max_length=32)),
                ('userfield', models.CharField(max_length=255)),
                ('recordingfile', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cdr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('callid', models.CharField(max_length=255)),
                ('queuename', models.CharField(max_length=128)),
                ('agent', models.CharField(max_length=128)),
                ('event', models.CharField(max_length=64)),
                ('data1', models.CharField(blank=True, max_length=255, null=True)),
                ('data2', models.CharField(blank=True, max_length=255, null=True)),
                ('data3', models.CharField(blank=True, max_length=255, null=True)),
                ('data4', models.CharField(blank=True, max_length=255, null=True)),
                ('data5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'queuelog',
                'ordering': ['-time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QueueMemberTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_name', models.CharField(max_length=128)),
                ('interface', models.CharField(max_length=255)),
                ('penalty', models.IntegerField()),
                ('paused', models.BooleanField()),
                ('member_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'queue_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentsNew',
            fields=[
                ('agent', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents_new',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QueuesNew',
            fields=[
                ('queuename', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('descr', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Queue',
                'verbose_name_plural': 'Queues',
                'db_table': 'queues_new',
                'managed': True,
            },
        ),
    ]
